// Date: 14.1.2016 17:11:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package ShadowGamerXY.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEnergyCube extends ModelBase
{
  //fields
    ModelRenderer Leg4;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg1;
    ModelRenderer Base1;
    ModelRenderer Shape1;
    ModelRenderer base2;
  
  public ModelEnergyCube()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Leg4 = new ModelRenderer(this, 0, 0);
      Leg4.addBox(-8F, 9F, -8F, 4, 14, 4);
      Leg4.setRotationPoint(0F, 0F, 0F);
      Leg4.setTextureSize(64, 64);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 0, 0);
      Leg2.addBox(4F, 9F, -8F, 4, 14, 4);
      Leg2.setRotationPoint(0F, 0F, 0F);
      Leg2.setTextureSize(64, 64);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 0, 0);
      Leg3.addBox(-8F, 9F, 4F, 4, 14, 4);
      Leg3.setRotationPoint(0F, 0F, 0F);
      Leg3.setTextureSize(64, 64);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg1 = new ModelRenderer(this, 0, 0);
      Leg1.addBox(4F, 9F, 4F, 4, 14, 4);
      Leg1.setRotationPoint(0F, 0F, 0F);
      Leg1.setTextureSize(64, 64);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Base1 = new ModelRenderer(this, 0, 46);
      Base1.addBox(-8F, 8F, -8F, 16, 1, 16);
      Base1.setRotationPoint(0F, 0F, 0F);
      Base1.setTextureSize(64, 64);
      Base1.mirror = true;
      setRotation(Base1, 0F, 0F, 0F);
      Shape1 = new ModelRenderer(this, 0, 20);
      Shape1.addBox(-7F, 9F, -6F, 13, 14, 12);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      base2 = new ModelRenderer(this, 0, 46);
      base2.addBox(-8F, 23F, -8F, 16, 1, 16);
      base2.setRotationPoint(0F, 0F, 0F);
      base2.setTextureSize(64, 64);
      base2.mirror = true;
      setRotation(base2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Leg4.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg1.render(f5);
    Base1.render(f5);
    Shape1.render(f5);
    base2.render(f5);
  }
  
  public void render(float f5)
  {
	  Leg4.render(f5);
	    Leg2.render(f5);
	    Leg3.render(f5);
	    Leg1.render(f5);
	    Base1.render(f5);
	    Shape1.render(f5);
	    base2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
