// Date: 26.12.2015 17:42:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package ShadowGamerXY.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelInfuser extends ModelBase
{
  //fields
    ModelRenderer Leg1;
    ModelRenderer Leg2;
    ModelRenderer Leg3;
    ModelRenderer Leg4;
    ModelRenderer Bottom;
    ModelRenderer Stick2;
    ModelRenderer Stick1;
    ModelRenderer Center;
    ModelRenderer Shape1;
    ModelRenderer Shape2;
  
  public ModelInfuser()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      Leg1 = new ModelRenderer(this, 30, 0);
      Leg1.addBox(-8F, 9F, 4F, 4, 12, 4);
      Leg1.setRotationPoint(0F, 0F, 0F);
      Leg1.setTextureSize(64, 64);
      Leg1.mirror = true;
      setRotation(Leg1, 0F, 0F, 0F);
      Leg2 = new ModelRenderer(this, 30, 21);
      Leg2.addBox(4F, 9F, -8F, 4, 12, 4);
      Leg2.setRotationPoint(0F, 0F, 0F);
      Leg2.setTextureSize(64, 64);
      Leg2.mirror = true;
      setRotation(Leg2, 0F, 0F, 0F);
      Leg3 = new ModelRenderer(this, 30, 0);
      Leg3.addBox(4F, 9F, 4F, 4, 12, 4);
      Leg3.setRotationPoint(0F, 0F, 0F);
      Leg3.setTextureSize(64, 64);
      Leg3.mirror = true;
      setRotation(Leg3, 0F, 0F, 0F);
      Leg4 = new ModelRenderer(this, 30, 0);
      Leg4.addBox(-8F, 9F, -8F, 4, 12, 4);
      Leg4.setRotationPoint(0F, 0F, 0F);
      Leg4.setTextureSize(64, 64);
      Leg4.mirror = true;
      setRotation(Leg4, 0F, 0F, 0F);
      Bottom = new ModelRenderer(this, 0, 43);
      Bottom.addBox(-8F, 21F, -8F, 16, 3, 16);
      Bottom.setRotationPoint(0F, 0F, 0F);
      Bottom.setTextureSize(64, 64);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      Stick2 = new ModelRenderer(this, 4, 15);
      Stick2.addBox(3F, 13F, -1F, 2, 9, 2);
      Stick2.setRotationPoint(0F, 0F, 0F);
      Stick2.setTextureSize(64, 64);
      Stick2.mirror = true;
      setRotation(Stick2, 0F, 0F, 0F);
      Stick1 = new ModelRenderer(this, 4, 15);
      Stick1.addBox(-5F, 13F, -1F, 2, 9, 2);
      Stick1.setRotationPoint(0F, 0F, 0F);
      Stick1.setTextureSize(64, 64);
      Stick1.mirror = true;
      setRotation(Stick1, 0F, 0F, 0F);
      Center = new ModelRenderer(this, 6, 2);
      Center.addBox(9F, 9.5F, -2F, 4, 4, 4);
      Center.setRotationPoint(0F, 0F, 0F);
      Center.setTextureSize(64, 64);
      Center.mirror = true;
      setRotation(Center, 0F, 0F, 0.7670891F);
      Shape1 = new ModelRenderer(this, 20, 16);
      Shape1.addBox(2F, 6F, -0.5F, 1, 8, 1);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(64, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0.4646765F);
      Shape2 = new ModelRenderer(this, 20, 16);
      Shape2.addBox(-3F, 6F, -0.5F, 1, 9, 1);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, -0.4646765F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Leg1.render(f5);
    Leg2.render(f5);
    Leg3.render(f5);
    Leg4.render(f5);
    Bottom.render(f5);
    Stick2.render(f5);
    Stick1.render(f5);
    Center.render(f5);
    Shape1.render(f5);
    Shape2.render(f5);
  }
  
  public void renderModel(float f5){
	  Leg1.render(f5);
	    Leg2.render(f5);
	    Leg3.render(f5);
	    Leg4.render(f5);
	    Bottom.render(f5);
	    Stick2.render(f5);
	    Stick1.render(f5);
	    Center.render(f5);
	    Shape1.render(f5);
	    Shape2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
